In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/final_project/data/naver_data.csv', encoding = 'cp949')

<ipython-input-8-6e46bafe0862>:1: DtypeWarning: Columns (18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/final_project/data/naver_data.csv', encoding = 'cp949')

# 건설사 nan값 채우기

In [ ]:
df_null = df[df['건설사'].isnull()]
df_null

In [ ]:
df_null_search = df_null[df_null["아파트명"].str.contains("편한")] #래미안, 힐스테이트, 디에이치, 푸르지오, 자이, e편한세상, 더샵, 롯데캐슬, SK뷰, 베르디움, 호반, 써밋,
df_null_search["아파트명"].unique()

In [ ]:
# 힐스테이트구성, 보라매자이더포레스트, e편한세상복현, 송도더샵파크애비뉴, 호반베르디움센트로포레, GS프라자, 호반, 여수블루써밋(도시형)

df[df['아파트명'] == '여수블루써밋(도시형)']

In [ ]:
df.loc[[84250,84251],'건설사'] = '현대건설'

df.loc[[124003,124004,124005,124006,124007,124008,124009],'건설사'] = 'GS건설'

df.loc[[29111,29112,29113,29114,29115,29116,29117	],'건설사'] = 'DL이앤씨'

df.loc[[43208,43209,43210,43211,43212,43213,43214,43215	],'건설사'] = 'POSCO이앤씨'

df.loc[[180485,180486,180487],'건설사'] = '호반건설'

df.loc[[135306],'건설사'] = 'GS건설'

df.loc[[192973,192974],'건설사'] = '호반건설'

df.loc[[171910,171911,171912,171913,171914,171915,171916,171917,171918,171919,171920],'건설사'] = '호반건설'

# 건설사 이름 통합

In [ ]:
str_re = "(주식회사|주|㈜|외1|외2|외3|외4|외)"

In [ ]:
df['건설사_ex'] = df.건설사.apply(lambda x : x.split(',')[0] if len(str(x).split(',')) > 1 else x)
df['건설사_ex'] = df.건설사_ex.apply(lambda x : x.split()[0] if len(str(x).split()) > 1 else x)
df['건설사_ex'] = df.건설사_ex.apply(lambda x : re.sub(r"[^\uAC00-\uD7A30-9a-zA-Z\s]", '', str(x)))
df['건설사_ex'] = df.건설사_ex.apply(lambda x : re.sub(str_re, '', str(x)))

In [ ]:
set(df.건설사_ex)

In [ ]:
print(df['건설사_ex'].unique())

# 건설사 시공능력 평가 순위
1. 삼성물산 - 래민안
2. 현대건설 - 힐스테이트
3. 대우건설 - 푸르지오
4. 현대엔지니어링 - 힐스테이트
5. 지에스건설 - 자이
6. 디앨이앤씨 - e편한세상
7. 포스코이앤씨 - 더샵
8. 롯데건설 - 롯데캐슬
9. 에스케이에코플랜트 - sk뷰
10. 호반건설 - 호반베르디움

# 삼성 건설사 이름 변경

In [ ]:
df_삼성 = df[df["건설사_ex"].str.contains("래미")] #삼성, samsung, 래

In [ ]:
df_삼성['건설사_ex'].unique()

array([], dtype=object)

In [ ]:
# 삼성물산 변경
df["건설사_ex"] = df["건설사_ex"].replace('삼성물산','삼성물산')
df["건설사_ex"] = df["건설사_ex"].replace('삼성종합건설','삼성물산')
df["건설사_ex"] = df["건설사_ex"].replace('삼성건설','삼성물산')
df["건설사_ex"] = df["건설사_ex"].replace('삼성물산식회','삼성물산') # 아파트이름이 래미안
df["건설사_ex"] = df["건설사_ex"].replace('삼성물산건설부문','삼성물산')
df["건설사_ex"] = df["건설사_ex"].replace('삼성건설롯데건설대우선경건설','삼성물산')
df["건설사_ex"] = df["건설사_ex"].replace('삼성물산택부문','삼성물산')

In [ ]:
df[df['건설사_ex']=='삼성종합건설']

Empty DataFrame
Columns: [아파트명, 면적, 법정동주소, 도로명주소, latitude, longitude, 세대수, 임대세대수, 최고층, 최저층, 용적률, 건폐율, 주차대수, 건설사, 난방, 공급면적, 전용면적, 전용율, 방수, 욕실수, 해당면적_세대수, 현관구조, 재산세, 재산세합계, 지방교육세, 재산세_도시지역분, 종합부동산세, 결정세액, 농어촌특별세, 가격, 겨울관리비, 여름관리비, 매매호가, 전세호가, 월세호가, 실거래가, 초등학교_학군정보, 초등학교_설립정보, 초등학교_남학생수, 초등학교_여학생수, 건설사_ex]
Index: []

[0 rows x 41 columns]

# 현대건설, 현대엔지니어링 건설사 이름변경

In [ ]:
df_현대 = df[df["건설사_ex"].str.contains("H")] # 현대, hyundai, 현다이, 힐, 에이치(디에이치), H
df_현대['건설사_ex'].unique()

array(['STH건설', 'KH종합건설', 'LH공사', 'HHI', 'HDC아이앤콘스', 'DH건설', 'HY건설',
       'HS종합건설', '대명HAT', '대영HAT'], dtype=object)

In [ ]:
# 현대건설 변경
df["건설사_ex"] = df["건설사_ex"].replace('현대','현대건설')
df["건설사_ex"] = df["건설사_ex"].replace('현대걸설','현대건설')
df["건설사_ex"] = df["건설사_ex"].replace('현대건설산업','현대건설')
# 현대산업개발
df["건설사_ex"] = df["건설사_ex"].replace('현대산업개발신동성개발','현대산업개발')
df["건설사_ex"] = df["건설사_ex"].replace('삼성건설롯데건설대우선경건설','현대산업개발')
df["건설사_ex"] = df["건설사_ex"].replace('현대산업','현대산업개발')
df["건설사_ex"] = df["건설사_ex"].replace('에이치디씨현대산업개발','현대산업개발')
df["건설사_ex"] = df["건설사_ex"].replace('현대상업개발','현대산업개발')
df["건설사_ex"] = df["건설사_ex"].replace('현대산업개발대림산업','현대산업개발')
df["건설사_ex"] = df["건설사_ex"].replace('HDC현대산업개발','현대산업개발')
df["건설사_ex"] = df["건설사_ex"].replace('현대산업개발대표','현대산업개발')

In [ ]:
df[df['건설사_ex']=='디에이치']

# 대우건설 건설사 이름변경

In [ ]:
df_대우 = df[df["건설사_ex"].str.contains("푸르")] # 대우, daewoo, 푸르
df_대우['건설사_ex'].unique()

array(['푸르메종합건설'], dtype=object)

In [ ]:
# 대우건설 변경
df["건설사_ex"] = df["건설사_ex"].replace('대우','대우건설')
df["건설사_ex"] = df["건설사_ex"].replace('대우건설','대우건설')
# 대우건설과 별개의 대우산업개발 회사 있음

In [ ]:
df[df['건설사_ex']=='대우']

Empty DataFrame
Columns: [아파트명, 면적, 법정동주소, 도로명주소, latitude, longitude, 세대수, 임대세대수, 최고층, 최저층, 용적률, 건폐율, 주차대수, 건설사, 난방, 공급면적, 전용면적, 전용율, 방수, 욕실수, 해당면적_세대수, 현관구조, 재산세, 재산세합계, 지방교육세, 재산세_도시지역분, 종합부동산세, 결정세액, 농어촌특별세, 가격, 겨울관리비, 여름관리비, 매매호가, 전세호가, 월세호가, 실거래가, 초등학교_학군정보, 초등학교_설립정보, 초등학교_남학생수, 초등학교_여학생수, 건설사_ex]
Index: []

[0 rows x 41 columns]

# 지에스건설 건설사 이름변경

In [65]:
df_지에스 = df[df["건설사_ex"].str.contains("럭키")] # 지에스, GS, gs, 자이
df_지에스['건설사_ex'].unique()
# LG건설

array(['럭키개발', '럭키건설', '럭키개발 ', '럭키종합건설', '유한럭키건설', '유럭키건설', '럭키산업개발',
       '럭키'], dtype=object)

In [69]:
# 대우건설 변경
df["건설사_ex"] = df["건설사_ex"].replace('지에스건설','GS건설')
df["건설사_ex"] = df["건설사_ex"].replace('GS건설','GS건설')
df["건설사_ex"] = df["건설사_ex"].replace('gs건설','GS건설')
df["건설사_ex"] = df["건설사_ex"].replace('엘지건설','GS건설')
df["건설사_ex"] = df["건설사_ex"].replace('엘지건설회사','GS건설')
df["건설사_ex"] = df["건설사_ex"].replace('럭키건설','GS건설')

In [68]:
df[df['건설사_ex']=='럭키']

,아파트명,면적,법정동주소,도로명주소,latitude,longitude,세대수,임대세대수,최고층,최저층,...,매매호가,전세호가,월세호가,실거래가,초등학교_학군정보,초등학교_설립정보,초등학교_남학생수,초등학교_여학생수,건설사_ex,top10
160426,소계럭키,65㎡,경상남도 창원시 의창구 소계동 468-1,경상남도 창원시 의창구 금강로379번길 16-9,35.260429,128.600807,243.0,0.0,15.0,9.0,...,"8,500",NaN,NaN,NaN,구암초등학교,공립,224.0,227.0,럭키,0
160427,소계럭키,71㎡,경상남도 창원시 의창구 소계동 468-1,경상남도 창원시 의창구 금강로379번길 16-9,35.260429,128.600807,243.0,0.0,15.0,9.0,...,1억 500,NaN,NaN,NaN,구암초등학교,공립,224.0,227.0,럭키,0
160428,소계럭키,79,경상남도 창원시 의창구 소계동 468-1,경상남도 창원시 의창구 금강로379번길 16-9,35.260429,128.600807,243.0,0.0,15.0,9.0,...,"1억 500~1억 4,000",NaN,NaN,NaN,구암초등학교,공립,224.0,227.0,럭키,0
163458,황성럭키,107㎡,경상북도 경주시 황성동 511,경상북도 경주시 황성로 35-6,35.867177,129.215426,353.0,0.0,15.0,11.0,...,"1억 6,500~1억 8,200",NaN,NaN,NaN,유림초등학교,공립,554.0,597.0,럭키,0
163459,황성럭키,184㎡,경상북도 경주시 황성동 511,경상북도 경주시 황성로 35-6,35.867177,129.215426,353.0,0.0,15.0,11.0,...,3억,NaN,NaN,NaN,유림초등학교,공립,554.0,597.0,럭키,0
163460,황성럭키,184,경상북도 경주시 황성동 511,경상북도 경주시 황성로 35-6,35.867177,129.215426,353.0,0.0,15.0,11.0,...,NaN,NaN,NaN,NaN,유림초등학교,공립,554.0,597.0,럭키,0

# 디앨이엔씨 건설사 이름변경

In [58]:
df_디앨이 = df[df["건설사_ex"].str.contains("DL")] # 디앨, DL, dl, 편한
df_디앨이['건설사_ex'].unique()

array(['DL이앤씨'], dtype=object)

In [ ]:
# 대우건설 변경

df["건설사_ex"] = df["건설사_ex"].replace('DL이앤씨','DL이앤씨')
df["건설사_ex"] = df["건설사_ex"].replace('DL건설','DL이앤씨')
df["건설사_ex"] = df["건설사_ex"].replace('대림산업','DL이앤씨')
df["건설사_ex"] = df["건설사_ex"].replace('대림건설','DL이앤씨')
df["건설사_ex"] = df["건설사_ex"].replace('대림','DL이앤씨')
df["건설사_ex"] = df["건설사_ex"].replace('대림산업대림산업','DL이앤씨')

In [ ]:
df[df['건설사_ex']=='DL건설']

Empty DataFrame
Columns: [아파트명, 면적, 법정동주소, 도로명주소, latitude, longitude, 세대수, 임대세대수, 최고층, 최저층, 용적률, 건폐율, 주차대수, 건설사, 난방, 공급면적, 전용면적, 전용율, 방수, 욕실수, 해당면적_세대수, 현관구조, 재산세, 재산세합계, 지방교육세, 재산세_도시지역분, 종합부동산세, 결정세액, 농어촌특별세, 가격, 겨울관리비, 여름관리비, 매매호가, 전세호가, 월세호가, 실거래가, 초등학교_학군정보, 초등학교_설립정보, 초등학교_남학생수, 초등학교_여학생수, 건설사_ex]
Index: []

[0 rows x 41 columns]

# 포스코이엔씨 건설사 이름변경

In [ ]:
df_포스코 = df[df["건설사_ex"].str.contains("#")] # 포스코, POSCO, posco, 샵, #
df_포스코['건설사_ex'].unique()

array([], dtype=object)

In [ ]:
# 포스코건설 변경
df["건설사_ex"] = df["건설사_ex"].replace('포스코건설','POSCO이앤씨')
df["건설사_ex"] = df["건설사_ex"].replace('포스코개발','POSCO이앤씨')
df["건설사_ex"] = df["건설사_ex"].replace('포스코이앤씨','POSCO이앤씨')

In [ ]:
df[df['건설사_ex']=='포스코건설']

Empty DataFrame
Columns: [아파트명, 면적, 법정동주소, 도로명주소, latitude, longitude, 세대수, 임대세대수, 최고층, 최저층, 용적률, 건폐율, 주차대수, 건설사, 난방, 공급면적, 전용면적, 전용율, 방수, 욕실수, 해당면적_세대수, 현관구조, 재산세, 재산세합계, 지방교육세, 재산세_도시지역분, 종합부동산세, 결정세액, 농어촌특별세, 가격, 겨울관리비, 여름관리비, 매매호가, 전세호가, 월세호가, 실거래가, 초등학교_학군정보, 초등학교_설립정보, 초등학교_남학생수, 초등학교_여학생수, 건설사_ex]
Index: []

[0 rows x 41 columns]

# 롯데건설 건설사 이름변경

In [ ]:
df_롯데 = df[df["건설사_ex"].str.contains("캐슬")] #롯데, lotte, LOTTE, 캐슬
df_롯데['건설사_ex'].unique()

array(['동양캐슬', '동영캐슬', '스타캐슬', '성재캐슬종합건설'], dtype=object)

In [ ]:
# 포스코건설 변경
df["건설사_ex"] = df["건설사_ex"].replace('롯데','롯데건설')

In [ ]:
df[df['건설사_ex']=='롯데']

Empty DataFrame
Columns: [아파트명, 면적, 법정동주소, 도로명주소, latitude, longitude, 세대수, 임대세대수, 최고층, 최저층, 용적률, 건폐율, 주차대수, 건설사, 난방, 공급면적, 전용면적, 전용율, 방수, 욕실수, 해당면적_세대수, 현관구조, 재산세, 재산세합계, 지방교육세, 재산세_도시지역분, 종합부동산세, 결정세액, 농어촌특별세, 가격, 겨울관리비, 여름관리비, 매매호가, 전세호가, 월세호가, 실거래가, 초등학교_학군정보, 초등학교_설립정보, 초등학교_남학생수, 초등학교_여학생수, 건설사_ex]
Index: []

[0 rows x 41 columns]

# 에스케이에코플랜트 건설사 이름변경

In [ ]:
df_sk = df[df["건설사_ex"].str.contains("view")] #sk, SK, 에스케이, 뷰, view
df_sk['건설사_ex'].unique()

array([], dtype=object)

In [ ]:
# 포스코건설 변경
df["건설사_ex"] = df["건설사_ex"].replace('sk건설','SK에코플랜트')
df["건설사_ex"] = df["건설사_ex"].replace('에스케이건설','SK에코플랜트')
df["건설사_ex"] = df["건설사_ex"].replace('에스케이에코플랜트','SK에코플랜트')
df["건설사_ex"] = df["건설사_ex"].replace('SK건설','SK에코플랜트')
df["건설사_ex"] = df["건설사_ex"].replace('SK에코플랜트','SK에코플랜트')

In [ ]:
df[df['건설사_ex']=='에스케이건설']

Empty DataFrame
Columns: [아파트명, 면적, 법정동주소, 도로명주소, latitude, longitude, 세대수, 임대세대수, 최고층, 최저층, 용적률, 건폐율, 주차대수, 건설사, 난방, 공급면적, 전용면적, 전용율, 방수, 욕실수, 해당면적_세대수, 현관구조, 재산세, 재산세합계, 지방교육세, 재산세_도시지역분, 종합부동산세, 결정세액, 농어촌특별세, 가격, 겨울관리비, 여름관리비, 매매호가, 전세호가, 월세호가, 실거래가, 초등학교_학군정보, 초등학교_설립정보, 초등학교_남학생수, 초등학교_여학생수, 건설사_ex]
Index: []

[0 rows x 41 columns]

# 호반건설 건설사 이름변경

In [ ]:
df_sk = df[df["건설사_ex"].str.contains("써밋")] #호반, hoban, 베르디움, 써밋
df_sk['건설사_ex'].unique()

array([], dtype=object)

In [ ]:
# 포스코건설 변경
df["건설사_ex"] = df["건설사_ex"].replace('우일건설산업호반건설산업','호반건설')
df["건설사_ex"] = df["건설사_ex"].replace('호반건설택','호반건설') # 베르디움, 써밋 브랜드 사용
df["건설사_ex"] = df["건설사_ex"].replace('호반산업','호반건설')
df["건설사_ex"] = df["건설사_ex"].replace('호반건설산업','호반건설')
df["건설사_ex"] = df["건설사_ex"].replace('호반산업개발','호반건설')
df["건설사_ex"] = df["건설사_ex"].replace('호반산업업','호반건설')
df["건설사_ex"] = df["건설사_ex"].replace('호반베르디움','호반건설')

In [ ]:
df[df['건설사_ex']=='호반베르디움']

Empty DataFrame
Columns: [아파트명, 면적, 법정동주소, 도로명주소, latitude, longitude, 세대수, 임대세대수, 최고층, 최저층, 용적률, 건폐율, 주차대수, 건설사, 난방, 공급면적, 전용면적, 전용율, 방수, 욕실수, 해당면적_세대수, 현관구조, 재산세, 재산세합계, 지방교육세, 재산세_도시지역분, 종합부동산세, 결정세액, 농어촌특별세, 가격, 겨울관리비, 여름관리비, 매매호가, 전세호가, 월세호가, 실거래가, 초등학교_학군정보, 초등학교_설립정보, 초등학교_남학생수, 초등학교_여학생수, 건설사_ex]
Index: []

[0 rows x 41 columns]

# 건설사 변경 확인

In [ ]:
set(df['건설사_ex'])

{'',
 '에스티씨종합건설',
 '예강총합건설',
 '효성건설PU',
 '케이엠씨건설',
 '태영종합건설',
 '유아도건설',
 '수근종합건설',
 '신우종합건설',
 '한라청학',
 'GQ종합건설',
 '근우건설',
 '네스코건설',
 '운암건설',
 '승지종합건설',
 '두유종합건설',
 '선두건설',
 '고건종합건설',
 '대윤종합건설',
 '우송종합건설',
 '나우피엔티',
 '엘림종합건설',
 '하오삼건설',
 '벡텔건설',
 '케이엔씨종합건설',
 '동서건설',
 '유진건설',
 '티엠건설',
 '비슬종합건설',
 '인석디앤씨',
 '유니크건설',
 '코랜드종합건설',
 '토미하우스',
 '동승건설',
 '동양캐슬',
 '동백종합건설',
 '예스홈서비스',
 '명월종합건설',
 '미추종합건설',
 '산태건설',
 '정흥종합건설',
 '흥산건설',
 '에프엠종합건설',
 '건종합건설',
 '우형종합건',
 '하나플러스건설',
 '합동진산업',
 '유안엔지니어링',
 '부영택',
 '루카스종합건설',
 '삼이건설',
 '보람종합건설',
 '두진공영',
 '신초건설',
 '한우택',
 '성창건설',
 '계룡산업건설',
 '대륭건설',
 '협화택',
 '영신',
 '경남기업',
 '도성건설',
 '대우건설',
 '한국친환경건설',
 '덕운건설',
 '정암건설',
 '경풍건설',
 '제이더블유종합건설',
 '지예종합건설',
 '삼해',
 '아일랜드개발',
 '풍성건설',
 '빌드앤건설',
 '신다산종합건설',
 '효마을종합건설',
 '태정종합건설',
 '휴스토리건설',
 '힐건설',
 '미라보건설',
 '해태제과',
 '봉림종합건설',
 '도담종합건설',
 '남미종합건설',
 '토우인종합건설',
 '금나종합건설',
 '서한',
 '파르네',
 '그룹가림건축',
 '신홍선건설',
 '세안건영한중택개발',
 '예반종합건설',
 '반석택',
 '해운건설',
 '장웅종합건설',
 '제이투종합건설',
 'TEC건설',
 '그린씨티종합건설',
 '부강종합건설',
 '한라건설합',
 '금강종합건설',
 '유진종합건설',
 '창신건설',
 '홍길택',
 '정토건설',
 '미화건설',
 '경두건설',
 '대교건설',
 '동부디엔씨유한회사',
 '장백건설',
 '예일종합건설',
 '으뜸엔지니어링',
 '보가건연',
 '삼덕진',
 '서연종합건설',
 '국보건설',
 '경남택',
 '우전건설',
 '차원종합건설',
 '우덜종합건설',
 '케이엔피종합건설',
 '미라벨종합건설',
 '인진건설',
 '혜성종합건설',
 '효산개발',
 '애드웰종합건설',
 '마조아종합건설',
 '동해택',
 '세화종합건설',
 '남경택종합건설',
 '대창기압',
 '진현건설',
 '해강건설',
 '중원건설산업',
 '엘지건설회사',
 '동현건설',
 'SA건설',
 '엠제이종합건설',
 '명승건설산업',
 '테크원종합건설',
 '금우건설',
 '조희종합건설',
 '대호',
 '길원종합건설',
 '천우신영종합건설',
 '건우산업개발',
 '세련종합건설',
 '하나건설이엔씨',
 '태헌건설',
 '베스아이건설부동산',
 '삼성택건설',
 '진한종합건설',
 '동남기업',
 '발해종합건설',
 '엔라이프건설',
 '스마트중앙건설',
 '성원토건',
 '부영건설',
 '녹천종합건설',
 '경성종합건설',
 '등명종합건설',
 '경상종합건설',
 '유니온',
 '만서택',
 '씨엔디공영',
 '한명종합건설',
 '창방종합건설',
 '창우',
 '장호택건설',
 '해남건설',
 '세담종합건설',
 '나천종합건설',
 '창현아엔지',
 '삼협건설',
 '라일종합건설',
 '씨엔우방',
 '광일개발',
 '인목개발',
 '유미지종합건설',
 '성심',
 '미조건설',
 '수목건축',
 '디자인스튜디오',
 '공릉종합건설',
 '금류건설',
 '제이엔종합건설',
 '유승건축사사무소',
 '소망종합건설',
 '휴림종합건설',
 '대경종합건설',
 '위일종합건설',
 '다진종합건설',
 '휴먼종합건설',
 '일신건설산업',
 '동양개발',
 '형남종합건설',
 '구룡종합건설',
 '신일기업',
 '청도솔리움',
 '서초건설',
 '에스디종합건설',
 '르가든',
 '태창',
 '영훈건설식회',
 '대명건설택',
 '신우아이에스종합건설',
 '채울건설',
 '새시대',
 '광덕종합건설',
 '덕원공영',
 '부원',
 '대영건설',
 'kc건설',
 '만금건설',
 '용웅산업',
 '한신공영',
 '세원',
 '경신택',
 '지앤지투자개발',
 '대구택공사',
 '지디종합건설',
 '신풍종합건설',
 '대보산업개발',
 '금광',
 '한신종합건설',
 '경호건설산업',
 '국인건설',
 '우미토건',
 '천해종합건설',
 '베네치아종합건설',
 '삼우택조합',
 '유청송종합건설',
 '더원건설',
 '남방건설',
 '팬더',
 '라사종합건설',
 '평광건설',
 '기인종합건축',
 '오양',
 '예림빌라트입자대표회',
 '바로종합건설',
 '대화택',
 '뉴성진종합건설',
 '키움건설',
 '오션건설',
 '삼두실업',
 '자인종합건설',
 '에이스산업개발',
 '후성종합건설',
 '성지택',
 '도영종합건설',
 '석영종합건설',
 '아라종합건설',
 '성',
 '새봄택',
 '이천일산업개발',
 '보성건축',
 '아나온개발',
 '성무종합건설',
 '현광종합건설',
 '대면종합건설',
 '에이치비',
 '두산중공업',
 '삼성택',
 '영광건설',
 '영진건설',
 '아공영',
 '천경종합건설',
 '삼원건설',
 '영무산업개발',
 '에스씨제일건설',
 '욱일건설',
 '세진종합건설',
 '킴스종합건설',
 '구구제종합토건',
 '씨엔지종합건설',
 '금아건설',
 '삼안종합건설',
 '현일건설',
 '경민',
 '동신건설',
 '삼보건설',
 '봉암종합건설',
 '한동종합건설',
 '대의피앤시',
 '신영건설',
 '흥화공업',
 '아이티종합건축',
 '하니건설이앤씨',
 '유성산업개발',
 '백구',
 '진안종합건설',
 '에이원건설',
 '쌍용',
 '희상건설',
 '화인산업',
 '정촌건설',
 '성도개발',
 '우성이엔씨',
 '도완종합건설',
 '수정건설',
 '디에이치종합건설',
 '강민산업개발',
 '국태종합건설',
 '동북종합건설',
 '대성에이스건설',
 '광덕건설',
 '우방건설',
 '비엠비건설',
 '광덕토건',
 'GV종합건설',
 '태서건설',
 '장풍건설',
 '두성엔지니어링건축사사무소',
 '두진종합건설',
 '화산건설',
 '송은종합건설',
 '금탑종합건설',
 '대웅디엔씨',
 '오른난종합건설',
 '예린종합건설',
 '지에이치종합건설',
 '왕궁건설',
 '삼미건설',
 '인터넷종합건설',
 '신세계건설',
 '대마종합건설',
 '백일건업',
 '설록종합건설',
 '백우종합건설',
 '금수종합건설',
 '임광토건',
 '형미종합건설',
 '태성',
 '에스케이하우징',
 '세양건설',
 '청하토건',
 '동성건설',
 '덕승종합건설',
 '율창건설',
 '태양건설',
 '명성종합건설',
 '대웅종합건설',
 '무학건설',
 '경보종합건설',
 '태호',
 '금강이앤씨',
 '지음건설',
 '원갑산업개발',
 '정원부르네오종합건설',
 '경수종합건설',
 '성풍건설',
 '종합건설리하',
 '디오',
 '성봉',
 '성장종합건설',
 '지성종합건설',
 '평지건설',
 '화남종합건설',
 '서광건설산업',
 '익성종합개발',
 '광명정대건설',
 '티오피종합건설',
 '우진인터비젼',
 '다원종합개발',
 '우경종합건설',
 '대호택건설',
 '성전건설',
 '미왕건설',
 '대유종합건설',
 '장미건설',
 '천광종합개발',
 '한국개발',
 '평진종합건설',
 '석건설',
 '해냄종합건설',
 '중흥',
 '케이앤디종합건설',
 '북종합건설',
 '부건종합건설',
 '해븐종합건설',
 '지성종합건축',
 '봉명종합건설',
 '석포종하건설',
 '대영',
 '왕종합건설',
 '아시아나항공',
 '태암택',
 '울트라건설',
 '유한회사영신토건',
 '삼창기업',
 '로미택건설',
 '에스티종합건설',
 '미리내종합건설',
 '평강건설',
 '명성건설',
 '유두레건설',
 '나라씨티건설',
 '대진종합건설',
 '드림개발',
 '뜰아래',
 '벽산',
 '희성종합건설',
 '쥬대양건설',
 '홍진택건설',
 '승보종합건설',
 '남우종합건설',
 '남광건설',
 '동삼건설',
 '스타앤종합건설',
 '서일건설',
 '홍일건설',
 '지드건설',
 '강남산업',
 '쌍용택',
 '의담건설',
 '동일건설',
 '엠코',
 '삼유건설',
 '엠그린조합건설',
 '지에스종합건설',
 '건양',
 '에이치엘디앤아이한라',
 '세모건설',
 '봉림종합선축사',
 '한미글로벌건축사사무소',
 '만민종합건설',
 'GB건설',
 '금왕종합건설',
 '디아인종합건설',
 '배연건설',
 '바인건설',
 '마디종합건설',
 '유구산건설',
 '상암종합건설',
 '효형종합건설',
 '신성씨앤씨건설',
 '금정종합건설',
 '대로건설',
 '합자회사밀성택',
 '삼화',
 '도한',
 '디엘인더스',
 '승일건설',
 '성신건설',
 '금미건설',
 '광진종합건설',
 '양제종합건설',
 '라인건설',
 '지우건설',
 '한미베이션',
 '토운',
 '리움건설',
 '청운건설',
 '디엘',
 '위너스종합건설',
 '복음',
 '선우건설',
 '우성디앤씨',
 '지보건설',
 '석제종합건설',
 '대방건설',
 '제이에스산업개발',
 '삼영',
 '남운개발',
 '아침종합건설',
 '성덕종합건설',
 '토렌스종합건설',
 '성아종합건설',
 '태곡종합건설',
 '태갑종합건설',
 '보령개발',
 '보미건설',
 '영인건설',
 '만호투제이건설',
 '무진선건설',
 '선원건설',
 '을해종합건설',
 '삼익종합건설',
 '제이엠',
 '동광건설',
 '희람종합건설',
 '곽산토건',
 '경상건설',
 '오광건설',
 '석종합건설',
 '목화산업',
 '합성공업공사',
 '태흥빌러스',
 '현개건설',
 '은탑산업개발',
 '유신형택건설',
 '아림택',
 '경풍종합건설',
 '상호산업',
 '홍익종합건업',
 '남광',
 '유경종합건설',
 '이앤아이건설',
 '보림건설',
 '국보종합건설',
 '백두개발',
 '삼인이앤씨',
 '에메랑드종합건설',
 '도시공감',
 '동일스위트',
 '세진씨엔에이치',
 '새한일',
 '엔아이씨종합건설',
 '성지우종합건설',
 '광남종합건설',
 '한복종합건설',
 '영풍산업',
 '재민종합건설',
 '신안토건',
 '화건설',
 '브이종합건설',
 '대신택',
 '월드건설사업',
 '승환종합건설',
 '한빛건설',
 '유관종합건설',
 '국일건설',
 '유안종합건설',
 '더블유에이치건설',
 '국도건설',
 '인텍택건설',
 '동덕건설',
 '신화산업',
 '씨제이엠종합건설',
 '브릿지종합건설',
 '대양산업건설',
 '지엔산업개발',
 '혜성',
 '금류',
 '우창건설',
 '우영건설',
 '정산',
 '우미택건설',
 '노건설',
 '남인건설',
 '건우',
 '신화토건',
 '아세만종합건설',
 '장방종합건설',
 '경방종건',
 '삼성탑종합건설',
 '동부이끌림',
 '대한송유관공사',
 '서종합건설',
 '고은건설',
 '가남종합건설',
 '신명산업개발',
 '삼풍',
 '리치건설',
 '엘리종합건설',
 '거봉종합건설',
 '다솜건설',
 '한섬종합건설',
 '오엔종합건설',
 '이앤에이건설',
 '찬동건설',
 '오승토건',
 '세민택건설',
 '재야건설',
 '일봉기업',
 '시티영화산업개발',
 '광영토건',
 '유현개발',
 '유하이스',
 '미우건설',
 '멘토이엔씨',
 '강남',
 '근화건설',
 '거명종합건설',
 '해태건설',
 '미건설',
 '성안종합건설',
 '정도건설',
 '동영종합건설',
 '성하디자인건설',
 '이에스엔지니어링건축사사무소',
 '필',
 '대이엔씨',
 '궁전택',
 '재상종합건설',
 '중앙RD',
 '석영건설',
 '제창종합건설',
 '신예건설',
 '혁진건설',
 '삼미타워맨션',
 '랭킹개발',
 '뉴피아종합건설',
 '와이엠종합건설',
 '한길건설',
 '삼익상사',
 '서안건설',
 '혁신종합건설',
 '협성종합건설',
 '삼웅건설',
 '양건설',
 '가든택',
 '신성',
 '엔트리윈산업개발',
 '한양',
 '삼일기업공사',
 '경양종합건설',
 '인서건설',
 '풍창종합건설',
 '한라종합건설',
 '재이와이종합건설',
 '티케이케미칼',
 '인수종합건설',
 '에스앤제이종합건설',
 '성호',
 '함경종합건설',
 '신화플러스건설',
 '삼익택',
 '흥화',
 '천명토건',
 '서울건축피씨엠건설',
 '지오에스건설',
 '하남건설',
 '에스투종합건설',
 '그린빌',
 '고아토건설',
 '정준종합건설',
 '금보종합건설',
 '송대건설',
 '오스빌종합건설',
 '민종합건설',
 '더블유에이와이',
 '신드림건설',
 '동원시스템즈',
 '신원',
 '대신건설택',
 '미성',
 '인화종합건설',
 '대우씨앤디',
 '신태진',
 '정진이앤씨',
 '예창종합건설',
 '제이오건설',
 '영진개발',
 '수지이엔씨',
 '에스제이종합건설',
 '미륭건설',
 '케이디종합건설',
 '동광종합토건',
 '국도종합건설',
 '대청건설',
 '에스티엑스건설산업',
 '시한종합건설',
 '정아종합건설',
 '스케마종합건설',
 '신아진흥건설',
 '한성프러스종합건설',
 '에스에스종합건설',
 '세연개발',
 '피아크건설',
 '금강에이치엔피종합건설',
 '해승종합건설',
 '계림이앤씨',
 '금호산업',
 '이노하우징',
 '대교종합건설',
 '앤하우스앤서비스',
 '반도건설',
 '서익종합건설',
 '금성건설',
 '지구종합건설',
 '안종합토건',
 '혁지종합건설',
 '대한건축사무소',
 '남성에이엔씨',
 '현대리모델링',
 '향목종합건설',
 '장호건설',
 '중앙택건설',
 '합자회사중흥택',
 '현지건설',
 '대자개발',
 '골든이앤시',
 '신웅종합건설',
 '안양3동성원지역택조합',
 '한성택조합',
 '삼영건설',
 '신안',
 '이조종합건설',
 '아성종합건설',
 '제이지택건설',
 '목화',
 '효창종합건설',
 '에스제이정암종합건설',
 '신원종합건설',
 '어웰종합건설',
 '17',
 '우리건설',
 '유',
 '다우택건설',
 '대제종합건설',
 '요신산업',
 '지엔씨종합건설',
 '유원택',
 '광신종합건설',
 '신방건설',
 '대양건설',
 '화산종합건설',
 '진우택건설',
 '유승토건',
 '경우크린텍',
 '경향종합건설',
 '협성종합건업',
 '와이케이종합건설',
 '대륙택개발',
 '대경토건',
 '선잉엠피종합건설',
 '삼종종합건설',
 '대우자판',
 '지성흥업종합건설',
 '이수건서',
 '대림택건설',
 '삼우종합',
 '삼환택',
 '동아건설',
 '서원건설',
 '티티건설',
 '청정종합건설',
 '보일건설',
 '지산택건설',
 '덕현건설',
 '나산종합선설',
 '하선종합건설',
 '다물종합건설',
 '제우스',
 '유니종합건설',
 '이원종합건설',
 '지엠에스종합건설',
 '두양건설',
 '명인종합건설',
 '길광종합건설',
 '유기반종합건설',
 '미택',
 '재성이십일종합건설',
 '벽상',
 '동아토건',
 '조흥이앤씨',
 '일양택',
 '삼중종합건설',
 '대월산업개발',
 '대림개발',
 '동준건설',
 '우택',
 '중방종합건설',
 '마스타건설',
 '유탑건설',
 '증흥건설',
 '서우택건영',
 '신일종합건설',
 '조형종합건설',
 '대평종합건설',
 '필건설',
 '거진종합건설',
 '도시콘스트럭숀',
 '해일종합건설',
 '경원미래건설',
 '엠디오종합건설',
 '혁종종합건설',
 '지산건설',
 '삼호택',
 '경희택',
 '천영종합건설',
 '국제토건',
 '새한종합건설',
 '리더종합건설',
 '동하건설',
 '하이빌건설',
 '신웅진',
 '렉스종합건설',
 '하이센스건설',
 '현강종합건설',
 '제일',
 '에이플러스종합건설',
 '삼안건설',
 '홍익택건설',
 '정립택',
 '청도건설',
 '가온씨앤에이',
 '늘푸른종합건설',
 '대망조합건설',
 '성창씨엔씨',
 '고려산업개발',
 '산수종건',
 '청어람종합건설',
 '더존건설',
 '남동경종합건설',
 '미래종합건설합자회사',
 '뉴스건설',
 '브엘세바',
 '천호택',
 '리첸건설',
 '중명건설',
 '휴안건설',
 '세양건설산업',
 '안진종합건설',
 '유건보건설',
 '나라원',
 '근명건설',
 '현진이엔씨',
 '우민종합건설',
 '삼웅종합건설',
 '가하건설',
 '무한건설',
 '동북건설',
 '에이스케이프건설',
 '예강건설',
 '호산견설',
 '제이디건설',
 '억조종합건설',
 '효준종합건설',
 '일해종합건설',
 '레이크건설',
 '제효',
 '태신',
 '유한회사초원건설',
 '부일이엔씨건설',
 '윤창택건설',
 '화수종합건설',
 '에이엠종합건',
 '판교종합건설',
 '건보종합건설',
 '대영에코건설',
 '강민종합건설',
 '골드종합건설',
 '세림종합건설',
 '청구택한라건설',
 '합우성건설',
 'YB종합건설',
 '애드케이',
 '가우디종합건설',
 '공영토건',
 '이도토건배실',
 '신천종합건설',
 '영심건설',
 '대신산업개발',
 '동인건설산업',
 '천천3리마을회',
 '동도종합건설',
 '비담종합건설',
 '뉴시공종합건설',
 '씨티건설',
 '순영종합건설',
 '장산종합건설',
 '일양종합건설',
 '건우걸설',
 '에스제이써미트유',
 '보덕건설',
 '우호건설',
 '삼성종합토건',
 '세왕종합건설',
 '화랑이엔씨',
 '케이에스씨지',
 '뉴빅종합건설',
 '더효종합건설',
 '두진건설',
 '우승종합건설',
 '두울예건',
 '삼정EC',
 '대구시',
 '대암종합건설',
 '대중종합건설',
 '이노건설',
 '현아종합건설',
 '광우택',
 '원흥택건설',
 '아이에스종합건설',
 '연희건설',
 '다인건설',
 '영천건설',
 '태평택건설',
 '일산업개발',
 '인평산업개발',
 '케이알산업',
 '두강건설',
 '성일개발',
 '1',
 '대원택건설',
 '탑스페이스건설',
 '한진건설',
 '한양양',
 '예림엔지니어링',
 '대건종합건설',
 '은일종합건설',
 '태종건설개발',
 '우미건설',
 '수지종합건설',
 '해람',
 '푸른건설',
 '청암택건설',
 '해금택',
 '예비종합건설',
 '시공종합건설',
 '상당종합건설',
 '중앙택',
 '덕일엔지니어링',
 '에스엠상선',
 '강남토건',
 '세대',
 '백마종합건설',
 '부영',
 '충일택건설',
 '성우종합건설',
 '해태',
 '한동산업',
 '21세기종합건설',
 '호용종합건설',
 '장한종합건설',
 '금강산종합건설',
 '용마산건설',
 '금강캐스빌종합건설',
 '현진건설',
 '금강산업',
 '엔트윈산업개발',
 '대원종합건설',
 '동보택건설',
 '대성기업개발',
 '진흥승일건설',
 '현우건설기술단',
 '금호개발',
 '세풍종합건설',
 '신호종합건설',
 '태평양건설',
 '우연종합건설',
 '심평종합건설',
 '케이티건설',
 '율포종합건설',
 '써니건설',
 '금강글로벌건설',
 '오복건설',
 '연안건설',
 '궁도종합건설',
 '갑목건설',
 '영재산업개발',
 '현대산업건설',
 '윤준종합건설',
 '보성중공업',
 '성진산업개발',
 '평산건설',
 '신부림씨엔씨',
 '합중흥택',
 '하택종합건설',
 '홍은종합건설',
 '삼풍종합토건',
 '용환건설',
 '청목건설',
 '길명종합건설',
 '스카이택건설',
 '한울종합토건',
 '효제종합건설',
 '삼우에스엔씨',
 '거화건설산업',
 '비에스건설회사',
 '채원건설',
 '럭키산업개발',
 '삼현건설',
 '송원건설',
 '익수종합건설',
 '민스건설',
 '참한종합건설',
 '한마음건설',
 '유예림',
 '일흥건설',
 '일두건설',
 '동광산업개발',
 '삼부토건',
 '씨앤엠종합건설',
 '남산건설',
 '수양건설',
 '동천건설',
 '종우개발',
 '태천종합건설',
 '조양연립재건축조합 ',
 '경북',
 '서진택건설',
 '미성토건',
 '정의개발',
 '중흥종합건걸',
 '열림종합건설',
 '대능택건설',
 '신우건설산업',
 '한인종합건설',
 '디',
 '백진종합건설',
 '라테르종합건설',
 '나린종합건설',
 '세우리',
 '씨',
 '케이티이엔에스',
 '세움종건',
 '요산종합건설',
 ...}

# 건설사 top10 컬럼 추가

- 1 ~ 5 : 삼성물산, 현대건설, 대우건설, 현대엔지니어링, 지에스건설
- 6 ~ 10 : 디엘이앤씨(대림산업), 포스코이앤씨(포스코건설), 롯데건설, 에스케이에코플랜트(에스케이건설), 호반건설

In [ ]:
df['top10'] = df['건설사_ex'].apply(lambda x: 1 if '삼성물산' in x
                                 else (1 if '현대건설' in x
                                       else (1 if '대우건설' in x
                                             else (1 if '현대엔지니어링' in x
                                                   else (1if 'GS건설' in x
                                                         else (1 if 'DL이앤씨' in x
                                                               else (1 if 'POSCO이앤씨' in x
                                                                     else (1 if '롯데건설' in x
                                                                           else (1 if 'SK에코플랜트' in x
                                                                                 else (1 if '호반건설' in x
                                             else 0))))))))))

In [ ]:
df['top10'].unique()

array([0, 1])

In [59]:
df[df['건설사_ex']=='현대건설']

,아파트명,면적,법정동주소,도로명주소,latitude,longitude,세대수,임대세대수,최고층,최저층,...,매매호가,전세호가,월세호가,실거래가,초등학교_학군정보,초등학교_설립정보,초등학교_남학생수,초등학교_여학생수,건설사_ex,top10
1162,현대그레이스,74A㎡,부산시 금정구 남산동 374-68,부산시 금정구 벅구산로 25-5,35.269223,129.094257,207.0,0.0,25.0,6.0,...,NaN,NaN,NaN,NaN,청룡초등학교,공립,261.0,225.0,현대건설,1
1163,현대그레이스,77B㎡,부산시 금정구 남산동 374-68,부산시 금정구 벅구산로 25-5,35.269223,129.094257,207.0,0.0,25.0,6.0,...,"1억 2,900~1억 3,600",NaN,NaN,NaN,청룡초등학교,공립,261.0,225.0,현대건설,1
1164,현대그레이스,107㎡,부산시 금정구 남산동 374-68,부산시 금정구 벅구산로 25-5,35.269223,129.094257,207.0,0.0,25.0,6.0,...,NaN,"1억 3,000","1,500/60~8,000/30","1,500/60~8,000/30",청룡초등학교,공립,261.0,225.0,현대건설,1
1165,현대그레이스,108B㎡,부산시 금정구 남산동 374-68,부산시 금정구 벅구산로 25-5,35.269223,129.094257,207.0,0.0,25.0,6.0,...,"1억 4,800~1억 8,000","1억 3,000",NaN,NaN,청룡초등학교,공립,261.0,225.0,현대건설,1
1166,현대그레이스,108A㎡,부산시 금정구 남산동 374-68,부산시 금정구 벅구산로 25-5,35.269223,129.094257,207.0,0.0,25.0,6.0,...,"1억 8,700~1억 9,000",NaN,NaN,NaN,청룡초등학교,공립,261.0,225.0,현대건설,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193112,소양로현대,145,강원도 춘천시 소양로2가 1,강원도 춘천시 모수물길 60,37.889143,127.727102,635.0,0.0,15.0,8.0,...,"2억 5,000~2억 8,000",NaN,NaN,NaN,근화초등학교,공립,105.0,110.0,현대건설,1
193444,현대5차,82㎡,강원도 춘천시 후평동 902,강원도 춘천시 후만로24번길 13,37.873786,127.749790,305.0,0.0,15.0,11.0,...,"1억 2,000~1억 4,000",NaN,NaN,NaN,부안초등학교,공립,481.0,459.0,현대건설,1
193445,현대5차,105,강원도 춘천시 후평동 902,강원도 춘천시 후만로24번길 13,37.873786,127.749790,305.0,0.0,15.0,11.0,...,NaN,NaN,NaN,NaN,부안초등학교,공립,481.0,459.0,현대건설,1
193521,현대,75㎡,강원도 태백시 황지동 665,강원도 태백시 해지개길 26,37.160842,128.983104,420.0,0.0,15.0,15.0,...,"9,900",NaN,NaN,NaN,NaN,NaN,NaN,NaN,현대건설,1
193522,현대,107,강원도 태백시 황지동 665,강원도 태백시 해지개길 26,37.160842,128.983104,420.0,0.0,15.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,현대건설,1